[package]
name = "verdure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
verdure-core = { path = "../verdure-core" }
verdure-ioc = { path = "../verdure-ioc" }
verdure-macros = { path = "../verdure-macros" }
inventory = { workspace = true }