[package]
name = "verdure-ioc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
verdure-core = { path = "../verdure-core" }
inventory = { workspace = true }
dashmap = { workspace = true }
[dev-dependencies]
